//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiProyecto.Models
{
    using System;
    
    public partial class getListPersons_Result4
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int NumeroDoc { get; set; }
        public string Email { get; set; }
        public string tipoDoc { get; set; }
        public System.DateTime feche_create { get; set; }
        public string id_identidicacion { get; set; }
        public string nombre_apellido { get; set; }
    }
}
